### ISSUE TITLE
/bin/sh: 1: /opt/installer/install.sh: not found

### ISSUE THREAD

**Issue by klaushauschild1984** [mcastellin/docker-hybris#6]
While following your instructions the image could not be build.
It fails at the point where install.sh should be executed. Where comes this file from? It is not contained in your repo. Do you assume that it is contained in my hybris copy?

**Comment by mcastellin** [comment]
Hi @klaushauschild1984,
it depends on the Hybris version you're currently using. For some versions, the initial setup is provided with `installer/install.sh` found inside the bundle archive.
What Hybris version are you running on?

**Comment by klaushauschild1984** [comment]
I am testing with 6.1.0.3
In my experience there was no need to invoke a install.sh

After remiving this step from Dockerfile I managed to create the image.

You could solve this by checking the existence of install.sh and optional invocation.

**Comment by mcastellin** [comment]
We are not going to maintain the existing image build process since we’re migrating to a new process. With the new commerce image generation the build process will be more generalised and will also allow customisation with custom sh scripts
